import type { StateContent } from './types'

// Generated by scripts/generate-state-content.ts — do not edit manually.
// Run: npx tsx scripts/generate-state-content.ts
export const stateContent: Record<string, Record<string, StateContent>> = {}

export function getStateContent(
  stateSlug: string,
  situationSlug: string,
): StateContent | null {
  return stateContent[stateSlug]?.[situationSlug] ?? null
}
