import { NextRequest, NextResponse } from 'next/server'

const RESEND_API_KEY = process.env.RESEND_API_KEY!
const MONITOR_EMAIL = 'anchor.offer.chatgpt@gmail.com'
const FROM = 'Helpful Homebuyers USA <no-reply@helpfulhomebuyersusa.com>'

async function sendEmail(to: string, subject: string, html: string) {
  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${RESEND_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ from: FROM, to, subject, html }),
  })
  if (!res.ok) {
    const err = await res.text()
    throw new Error(`Resend error ${res.status}: ${err}`)
  }
  return res.json()
}

function fmt(n: number) {
  return n.toLocaleString('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 })
}

function compsTable(comps: any[]) {
  if (!comps?.length) return '<p>No comps selected.</p>'
  const rows = comps.map((c: any) => `
    <tr>
      <td style="padding:6px 10px;border-bottom:1px solid #333">${c.address}</td>
      <td style="padding:6px 10px;border-bottom:1px solid #333;text-align:right">${fmt(c.sale_price)}</td>
      <td style="padding:6px 10px;border-bottom:1px solid #333;text-align:right">${c.sqft?.toLocaleString() ?? '—'} sf</td>
      <td style="padding:6px 10px;border-bottom:1px solid #333;text-align:right">${c.beds}bd / ${c.baths}ba</td>
      <td style="padding:6px 10px;border-bottom:1px solid #333">${c.sale_date || '—'}</td>
      <td style="padding:6px 10px;border-bottom:1px solid #333">${c.source}</td>
    </tr>`).join('')
  return `
    <table style="width:100%;border-collapse:collapse;font-size:13px">
      <thead>
        <tr style="background:#1a1a1a;color:#aaa">
          <th style="padding:8px 10px;text-align:left">Address</th>
          <th style="padding:8px 10px;text-align:right">Sale Price</th>
          <th style="padding:8px 10px;text-align:right">Size</th>
          <th style="padding:8px 10px;text-align:right">Bed/Bath</th>
          <th style="padding:8px 10px;text-align:left">Date</th>
          <th style="padding:8px 10px;text-align:left">Source</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>`
}

function userResultsHtml(data: {
  address: string
  arv: any
  pairedComps: any[]
  repairs: number
  maxOffer: number
}) {
  const { address, arv, pairedComps, repairs, maxOffer } = data
  const spread = arv.high - arv.low
  const spreadPct = arv.low > 0 ? ((spread / arv.low) * 100).toFixed(1) : '0'

  return `
    <div style="font-family:sans-serif;background:#111;color:#e5e5e5;padding:32px;max-width:680px;margin:0 auto;border-radius:8px">
      <h2 style="color:#22c55e;margin:0 0 4px">Comp Analysis Results</h2>
      <p style="color:#888;margin:0 0 24px;font-size:13px">Helpful Homebuyers USA — Property Valuation Tool</p>

      <h3 style="color:#fff;font-size:15px;margin:0 0 8px">Subject Property</h3>
      <p style="margin:0 0 24px;color:#ccc">${address}</p>

      <h3 style="color:#fff;font-size:15px;margin:0 0 12px">Selected Comps (${pairedComps.length})</h3>
      ${compsTable(pairedComps)}

      <h3 style="color:#fff;font-size:15px;margin:24px 0 12px">ARV Range</h3>
      <table style="font-size:14px;border-collapse:collapse;width:100%">
        <tr>
          <td style="padding:6px 0;color:#aaa">Low</td>
          <td style="padding:6px 0;color:#fff;text-align:right">${fmt(arv.low)}</td>
        </tr>
        <tr>
          <td style="padding:6px 0;color:#aaa">High</td>
          <td style="padding:6px 0;color:#fff;text-align:right">${fmt(arv.high)}</td>
        </tr>
        <tr>
          <td style="padding:6px 0;color:#aaa">Delta Spread</td>
          <td style="padding:6px 0;color:${parseFloat(spreadPct) > 25 ? '#f59e0b' : '#22c55e'};text-align:right">${fmt(spread)} (${spreadPct}%)</td>
        </tr>
        <tr>
          <td style="padding:6px 0;color:#aaa">$/sqft</td>
          <td style="padding:6px 0;color:#fff;text-align:right">${fmt(arv.median_ppsf)}/sf</td>
        </tr>
      </table>

      ${repairs > 0 ? `
      <h3 style="color:#fff;font-size:15px;margin:24px 0 12px">Offer Calculation</h3>
      <table style="font-size:14px;border-collapse:collapse;width:100%">
        <tr>
          <td style="padding:6px 0;color:#aaa">Repairs</td>
          <td style="padding:6px 0;color:#fff;text-align:right">− ${fmt(repairs)}</td>
        </tr>
        <tr style="border-top:1px solid #333">
          <td style="padding:10px 0 6px;color:#22c55e;font-weight:bold">Max Offer (90%)</td>
          <td style="padding:10px 0 6px;color:#22c55e;font-weight:bold;text-align:right">${fmt(maxOffer)}</td>
        </tr>
      </table>` : ''}

      <p style="margin:32px 0 0;font-size:12px;color:#555">
        Generated by Helpful Homebuyers USA · helpfulhomebuyersusa.com/comps
      </p>
    </div>`
}

function monitorHtml(data: {
  userEmail: string
  address: string
  sqft: number
  condition: string
  arv: any
  pairedComps: any[]
  allCompsCount: number
  repairs: number
  maxOffer: number
  timestamp: string
  ip: string
}) {
  return `
    <div style="font-family:monospace;background:#0a0a0a;color:#e5e5e5;padding:24px;max-width:700px;border-radius:6px">
      <h2 style="color:#22c55e;font-family:sans-serif;margin:0 0 16px">/comps Usage Log</h2>
      <table style="font-size:13px;border-collapse:collapse;width:100%">
        <tr><td style="color:#888;padding:4px 12px 4px 0;white-space:nowrap">Time</td><td style="color:#fff">${data.timestamp}</td></tr>
        <tr><td style="color:#888;padding:4px 12px 4px 0">User Email</td><td style="color:#22c55e">${data.userEmail || '(anonymous)'}</td></tr>
        <tr><td style="color:#888;padding:4px 12px 4px 0">IP</td><td style="color:#fff">${data.ip}</td></tr>
        <tr><td style="color:#888;padding:4px 12px 4px 0">Address</td><td style="color:#fff">${data.address}</td></tr>
        <tr><td style="color:#888;padding:4px 12px 4px 0">Sqft</td><td style="color:#fff">${data.sqft?.toLocaleString()}</td></tr>
        <tr><td style="color:#888;padding:4px 12px 4px 0">Condition</td><td style="color:#fff">${data.condition}</td></tr>
        <tr><td style="color:#888;padding:4px 12px 4px 0">Comps (bulk / selected)</td><td style="color:#fff">${data.allCompsCount} / ${data.pairedComps.length}</td></tr>
        <tr><td style="color:#888;padding:4px 12px 4px 0">ARV Range</td><td style="color:#fff">${fmt(data.arv.low)} – ${fmt(data.arv.high)}</td></tr>
        <tr><td style="color:#888;padding:4px 12px 4px 0">$/sqft</td><td style="color:#fff">${fmt(data.arv.median_ppsf)}/sf</td></tr>
        ${data.repairs > 0 ? `<tr><td style="color:#888;padding:4px 12px 4px 0">Repairs</td><td style="color:#f59e0b">${fmt(data.repairs)}</td></tr>
        <tr><td style="color:#888;padding:4px 12px 4px 0">Max Offer (90%)</td><td style="color:#22c55e;font-weight:bold">${fmt(data.maxOffer)}</td></tr>` : ''}
      </table>

      <h3 style="color:#aaa;font-size:13px;margin:20px 0 8px">Selected Comps</h3>
      ${compsTable(data.pairedComps)}
    </div>`
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    const {
      userEmail,
      address,
      sqft,
      condition,
      arv,
      pairedComps,
      allCompsCount,
      repairs = 0,
      maxOffer = 0,
    } = body

    const timestamp = new Date().toLocaleString('en-US', { timeZone: 'America/New_York' })
    const ip = req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || 'unknown'

    const sends: Promise<any>[] = []

    // 1. Usage log to monitoring inbox (always)
    sends.push(
      sendEmail(
        MONITOR_EMAIL,
        `[comps] ${address} — ${userEmail || 'anonymous'}`,
        monitorHtml({ userEmail, address, sqft, condition, arv, pairedComps, allCompsCount, repairs, maxOffer, timestamp, ip })
      ).catch(err => console.error('[monitor email]', err))
    )

    // 2. Results to user (only if they provided an email)
    if (userEmail?.includes('@')) {
      sends.push(
        sendEmail(
          userEmail,
          `Your comp analysis: ${address}`,
          userResultsHtml({ address, arv, pairedComps, repairs, maxOffer })
        ).catch(err => console.error('[user email]', err))
      )
    }

    await Promise.all(sends)
    return NextResponse.json({ ok: true })
  } catch (err: any) {
    console.error('[comps-notify]', err)
    return NextResponse.json({ ok: false, error: err.message }, { status: 500 })
  }
}
